"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarDays, Landmark, Pencil, Plus, Target, Trash2 } from "lucide-react";
import type { Route } from "next";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";

import { MobileShell } from "@/components/layout/mobile-shell";
import { PageHeader } from "@/components/layout/page-header";
import { Drawer, DrawerClose, DrawerContent, DrawerDescription, DrawerFooter, DrawerHeader, DrawerTitle } from "@/components/ui/drawer";
import { ProgressBar } from "@/components/ui/progress-bar";
import { formatMoney } from "@/lib/home/view-model";
import { createSavingsTransfer, deleteSavingsGoal, getGoalEditorData } from "@/lib/plans/api";
import { isPositiveMoney, preferredGoalAccount, progressPercent } from "@/lib/plans/utils";
import { localDateTime } from "@/lib/recurring/utils";

export function GoalDetail({ goalId }: { goalId: string }) {
  const router = useRouter(); const queryClient = useQueryClient();
  const detail = useQuery({ queryFn: () => getGoalEditorData(goalId), queryKey: ["goal-detail", goalId] });
  const [contributionOpen, setContributionOpen] = useState(false); const [deleteOpen, setDeleteOpen] = useState(false); const [accountId, setAccountId] = useState(""); const [amount, setAmount] = useState(""); const [date, setDate] = useState(localDateTime); const [note, setNote] = useState(""); const [error, setError] = useState<string | null>(null);
  const goal = detail.data?.goal; const matchingAccounts = detail.data?.accounts.filter((account) => account.currency === goal?.currency) ?? [];
  const selectedAccountId = accountId || (goal && detail.data ? preferredGoalAccount(detail.data.accounts, goal.currency)?.id : undefined) || "";
  const contribute = useMutation({ mutationFn: async () => { if (!goal) throw new Error("Goal is unavailable."); if (!selectedAccountId) throw new Error(`Add an active ${goal.currency} account before contributing.`); if (!isPositiveMoney(amount)) throw new Error("Enter a positive contribution amount."); return createSavingsTransfer({ amount, description: note.trim() || null, from_account_id: selectedAccountId, savings_goal_id: goal.id, transaction_at: new Date(date).toISOString() }, crypto.randomUUID()); }, onSuccess: async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ["goal-detail", goalId] }), queryClient.invalidateQueries({ queryKey: ["goals"] }), queryClient.invalidateQueries({ queryKey: ["accounts"] }), queryClient.invalidateQueries({ queryKey: ["home"] }), queryClient.invalidateQueries({ queryKey: ["transactions"] })]); setAmount(""); setNote(""); setContributionOpen(false); }, onError: (cause) => setError(cause instanceof Error ? cause.message : "Unable to add money.") });
  const remove = useMutation({ mutationFn: deleteSavingsGoal });
  async function confirmDelete() { setError(null); try { await remove.mutateAsync(goalId); await queryClient.invalidateQueries({ queryKey: ["goals"] }); router.replace("/goal" as Route); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to delete this goal."); } }
  function submitContribution(event: FormEvent) { event.preventDefault(); setError(null); contribute.mutate(); }
  const percent = progressPercent(goal?.progress.percent_complete ?? "0");
  return <MobileShell><div className="standard-page goal-detail-page"><PageHeader backHref={"/goal" as Route} title="Goal details" />{detail.isPending ? <div aria-busy="true" className="transaction-form-skeleton" /> : null}{detail.isError ? <section className="transaction-history-error" role="alert"><strong>Couldn’t load this goal</strong><p>{detail.error.message}</p><button onClick={() => void detail.refetch()} type="button">Try again</button></section> : null}{goal ? <><section className="goal-detail-hero"><span><Target aria-hidden="true" size={26} /></span><p>{goal.status}</p><h2>{goal.name}</h2><strong>{formatMoney(goal.progress.saved_amount, goal.currency)}</strong><small>of {formatMoney(goal.target_amount, goal.currency)}</small><ProgressBar accent="purple" label={`${goal.name} progress`} value={percent} /><p>{Math.round(percent)}% complete · {formatMoney(goal.progress.remaining_amount, goal.currency)} left</p></section><section className="transaction-detail-facts"><div><Target aria-hidden="true" size={17} /><span>Monthly target</span><strong>{formatMoney(goal.monthly_target_amount, goal.currency)}</strong></div><div><CalendarDays aria-hidden="true" size={17} /><span>Target date</span><strong>{goal.target_date ? new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(`${goal.target_date}T00:00:00`)) : "No deadline"}</strong></div>{goal.note ? <div><Target aria-hidden="true" size={17} /><span>Note</span><strong>{goal.note}</strong></div> : null}</section><section aria-label="Goal actions" className="goal-detail-actions"><Link href={`/goal/${goal.id}/edit` as Route}><Pencil aria-hidden="true" size={17} />Edit goal</Link>{goal.status === "active" ? <button onClick={() => { setError(null); setContributionOpen(true); }} type="button"><Plus aria-hidden="true" size={17} />Add money</button> : null}<button className="goal-delete-button" onClick={() => { setError(null); setDeleteOpen(true); }} type="button"><Trash2 aria-hidden="true" size={17} />Delete goal</button></section></> : null}
    <Drawer onOpenChange={setContributionOpen} open={contributionOpen}><DrawerContent><form onSubmit={submitContribution}><DrawerHeader><DrawerTitle>Add money to {goal?.name}</DrawerTitle><DrawerDescription>This moves money from the selected account and records it toward the goal.</DrawerDescription></DrawerHeader><div className="goal-contribution-fields"><label><span><Landmark aria-hidden="true" size={16} />From account</span><select aria-label="Contribution account" disabled={!matchingAccounts.length} onChange={(event) => setAccountId(event.target.value)} value={selectedAccountId}>{!matchingAccounts.length ? <option value="">No {goal?.currency} account available</option> : null}{matchingAccounts.map((account) => <option key={account.id} value={account.id}>{account.name} · {formatMoney(account.current_balance, account.currency)}</option>)}</select></label>{!matchingAccounts.length && goal ? <Link className="setup-inline-action" href={`/accounts/new?currency=${encodeURIComponent(goal.currency)}&next=${encodeURIComponent(`/goal/${goal.id}`)}` as Route}><Landmark aria-hidden="true" size={16} />Add a {goal.currency} account</Link> : null}<label><span>Amount</span><input aria-label="Contribution amount" inputMode="decimal" onChange={(event) => setAmount(event.target.value)} placeholder="0.00" value={amount} /></label><label><span>Date</span><input aria-label="Contribution date" onChange={(event) => setDate(event.target.value)} type="datetime-local" value={date} /></label><label><span>Note (optional)</span><textarea aria-label="Contribution note" onChange={(event) => setNote(event.target.value)} rows={2} value={note} /></label></div>{error ? <p className="drawer-error" role="alert">{error}</p> : null}<DrawerFooter><button className="reminder-confirm-button" disabled={contribute.isPending || !matchingAccounts.length} type="submit">{contribute.isPending ? "Adding…" : "Add money"}</button><DrawerClose asChild><button className="drawer-close-button" type="button">Cancel</button></DrawerClose></DrawerFooter></form></DrawerContent></Drawer>
    <Drawer onOpenChange={setDeleteOpen} open={deleteOpen}><DrawerContent><DrawerHeader><DrawerTitle>Delete {goal?.name}?</DrawerTitle><DrawerDescription>The goal will be archived. Existing transfers and account history remain unchanged.</DrawerDescription></DrawerHeader>{error ? <p className="drawer-error" role="alert">{error}</p> : null}<DrawerFooter><button className="drawer-danger-button" disabled={remove.isPending} onClick={() => void confirmDelete()} type="button">{remove.isPending ? "Deleting…" : "Delete goal"}</button><DrawerClose asChild><button className="drawer-close-button" type="button">Keep goal</button></DrawerClose></DrawerFooter></DrawerContent></Drawer>
  </div></MobileShell>;
}
