"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { Route } from "next";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import { MobileShell } from "@/components/layout/mobile-shell";
import { PageHeader } from "@/components/layout/page-header";
import { createLoanRecord, getLoanEditorData, updateLoanRecord } from "@/lib/loans/api";
import { isPositiveMoney, localDateTime } from "@/lib/loans/utils";

type EditorData = Awaited<ReturnType<typeof getLoanEditorData>>;
function LoanEditor({ data, recordId }: { data: EditorData; recordId?: string }) {
  const router = useRouter(); const queryClient = useQueryClient(); const record = data.record;
  const [direction, setDirection] = useState(record?.direction ?? "given"); const [personId, setPersonId] = useState(record?.person_id ?? data.people[0]?.id ?? ""); const [accountId, setAccountId] = useState(record?.account_id ?? data.accounts.find((account) => account.is_default)?.id ?? data.accounts[0]?.id ?? ""); const [amount, setAmount] = useState(record?.principal_amount ?? ""); const [issuedAt, setIssuedAt] = useState(record ? localDateTime(new Date(record.issued_at)) : localDateTime()); const [repayDate, setRepayDate] = useState(record?.repay_date ?? ""); const [note, setNote] = useState(record?.note ?? ""); const [error, setError] = useState<string | null>(null);
  const selectedAccount = data.accounts.find((account) => account.id === accountId); const currency = selectedAccount?.currency ?? record?.currency ?? "USD";
  const save = useMutation({ mutationFn: async () => { if (!personId) throw new Error("Choose a loan contact."); if (!accountId) throw new Error("Choose an active account."); if (!isPositiveMoney(amount)) throw new Error("Enter a positive loan amount."); if (!repayDate) throw new Error("Choose a repayment date."); if (repayDate < issuedAt.slice(0, 10)) throw new Error("Repayment date cannot be before the loan date."); const payload = { account_id: accountId, currency, direction, issued_at: new Date(issuedAt).toISOString(), note: note.trim() || null, person_id: personId, principal_amount: amount, repay_date: repayDate } as const; return recordId ? updateLoanRecord(recordId, payload) : createLoanRecord(payload); }, onSuccess: async (saved) => { await Promise.all([queryClient.invalidateQueries({ queryKey: ["loans"] }), queryClient.invalidateQueries({ queryKey: ["loan-detail", saved.id] })]); router.replace(`/loan/${saved.id}` as Route); }, onError: (cause) => setError(cause instanceof Error ? cause.message : "Unable to save this loan.") });
  function submit(event: FormEvent) { event.preventDefault(); setError(null); save.mutate(); }
  return <form className="loan-form" onSubmit={submit}><section className="loan-form-intro"><p className="eyebrow">{direction === "given" ? "MONEY YOU GAVE" : "MONEY YOU BORROWED"}</p><h2>{direction === "given" ? "Keep repayment expectations clear." : "Know exactly what you need to repay."}</h2></section><div aria-label="Loan direction" className="transaction-kind-tabs loan-direction-tabs"><button aria-pressed={direction === "given"} onClick={() => setDirection("given")} type="button">I gave money</button><button aria-pressed={direction === "taken"} onClick={() => setDirection("taken")} type="button">I borrowed</button></div><div className="form-card"><label className="transaction-field"><span>Contact</span><select aria-label="Loan contact" onChange={(event) => setPersonId(event.target.value)} value={personId}><option value="">Choose a contact</option>{data.people.map((person) => <option key={person.id} value={person.id}>{person.name} · {person.phone_number}</option>)}</select>{!data.people.length ? <small>Need a contact? <Link href={"/loan/people/new" as Route}>Add one first</Link>.</small> : null}</label><label className="transaction-field"><span>Account</span><select aria-label="Loan account" onChange={(event) => setAccountId(event.target.value)} value={accountId}><option value="">Choose an account</option>{data.accounts.map((account) => <option key={account.id} value={account.id}>{account.name} · {account.currency}</option>)}</select></label><label className="transaction-field"><span>Amount</span><input aria-label="Loan amount" inputMode="decimal" onChange={(event) => setAmount(event.target.value)} placeholder="0.00" value={amount} /></label><label className="transaction-field"><span>{direction === "given" ? "Given date" : "Borrowed date"}</span><input aria-label="Loan date" onChange={(event) => setIssuedAt(event.target.value)} type="datetime-local" value={issuedAt} /></label><label className="transaction-field"><span>{direction === "given" ? "Expected return" : "Repay by"}</span><input aria-label="Repayment date" min={issuedAt.slice(0, 10)} onChange={(event) => setRepayDate(event.target.value)} type="date" value={repayDate} /></label><label className="transaction-field"><span>Note (optional)</span><textarea aria-label="Loan note" maxLength={500} onChange={(event) => setNote(event.target.value)} rows={3} value={note} /></label></div>{error ? <p className="form-error" role="alert">{error}</p> : null}<button className="save-transaction-button" disabled={save.isPending} type="submit">{save.isPending ? "Saving…" : recordId ? "Save loan" : direction === "given" ? "Create given loan" : "Create borrowed loan"}</button></form>;
}
export function LoanForm({ recordId }: { recordId?: string }) { const editor = useQuery({ queryFn: () => getLoanEditorData(recordId), queryKey: ["loan-editor", recordId ?? "new"] }); return <MobileShell><div className="standard-page loan-form-page"><PageHeader backHref={(recordId ? `/loan/${recordId}` : "/loan") as Route} title={recordId ? "Edit loan" : "New loan"} />{editor.isPending ? <div aria-busy="true" className="transaction-form-skeleton" /> : null}{editor.isError ? <section className="transaction-history-error" role="alert"><strong>Couldn’t load loan form</strong><p>{editor.error.message}</p><button onClick={() => void editor.refetch()} type="button">Try again</button></section> : null}{editor.data ? <LoanEditor data={editor.data} key={editor.dataUpdatedAt} recordId={recordId} /> : null}</div></MobileShell>; }
