"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ChevronRight, Plus, Trash2, UsersRound } from "lucide-react";
import type { Route } from "next";
import Link from "next/link";
import { useState } from "react";
import { MobileShell } from "@/components/layout/mobile-shell";
import { PageHeader } from "@/components/layout/page-header";
import { Drawer, DrawerClose, DrawerContent, DrawerDescription, DrawerFooter, DrawerHeader, DrawerTitle } from "@/components/ui/drawer";
import { deleteLoanPerson, getLoanPeople } from "@/lib/loans/api";
import type { LoanPerson } from "@/lib/loans/types";

export function PeopleDashboard() { const queryClient = useQueryClient(); const people = useQuery({ queryFn: getLoanPeople, queryKey: ["loan-people"] }); const [selected, setSelected] = useState<LoanPerson | null>(null); const [error, setError] = useState<string | null>(null); const remove = useMutation({ mutationFn: deleteLoanPerson }); async function confirm() { if (!selected) return; setError(null); try { await remove.mutateAsync(selected.id); await Promise.all([queryClient.invalidateQueries({ queryKey: ["loan-people"] }), queryClient.invalidateQueries({ queryKey: ["loans"] })]); setSelected(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to archive this contact."); } }
  return <MobileShell><div className="standard-page loan-people-page"><PageHeader backHref={"/loan" as Route} title="Loan people" trailing={<Link aria-label="Add loan person" className="transaction-header-add" href={"/loan/people/new" as Route}><Plus aria-hidden="true" size={20} /></Link>} /><section className="people-intro"><span><UsersRound aria-hidden="true" size={22} /></span><div><p className="eyebrow">YOUR CONTACTS</p><h2>Keep loan details attached to a real person.</h2></div></section>{people.isPending ? <div aria-busy="true" className="transaction-form-skeleton" /> : null}{people.isError ? <section className="transaction-history-error" role="alert"><strong>Couldn’t load contacts</strong><p>{people.error.message}</p><button onClick={() => void people.refetch()} type="button">Try again</button></section> : null}{people.data ? <div className="loan-people-list">{people.data.length ? people.data.map((person) => <article key={person.id}><Link href={`/loan/people/${person.id}/edit` as Route}><span className="category-icon accent-blue"><UsersRound aria-hidden="true" size={18} /></span><span><strong>{person.name}</strong><small>{person.phone_number}{person.note ? ` · ${person.note}` : ""}</small></span><ChevronRight aria-hidden="true" size={16} /></Link><button aria-label={`Delete ${person.name}`} onClick={() => { setError(null); setSelected(person); }} type="button"><Trash2 aria-hidden="true" size={16} /></button></article>) : <div className="plan-empty-card"><UsersRound aria-hidden="true" size={24} /><strong>No loan contacts</strong><p>Add the people connected to money you lend or borrow.</p><Link href={"/loan/people/new" as Route}>Add a contact <ChevronRight aria-hidden="true" size={15} /></Link></div>}</div> : null}<Drawer onOpenChange={(open) => { if (!open) setSelected(null); }} open={Boolean(selected)}><DrawerContent><DrawerHeader><DrawerTitle>Delete {selected?.name}?</DrawerTitle><DrawerDescription>This archives the contact. Existing loan records remain visible in history.</DrawerDescription></DrawerHeader>{error ? <p className="drawer-error" role="alert">{error}</p> : null}<DrawerFooter><button className="drawer-danger-button" disabled={remove.isPending} onClick={() => void confirm()} type="button">{remove.isPending ? "Deleting…" : "Delete contact"}</button><DrawerClose asChild><button className="drawer-close-button" type="button">Keep contact</button></DrawerClose></DrawerFooter></DrawerContent></Drawer></div></MobileShell>; }
