"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { Route } from "next";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import { MobileShell } from "@/components/layout/mobile-shell";
import { PageHeader } from "@/components/layout/page-header";
import { createLoanPerson, getLoanPerson, updateLoanPerson } from "@/lib/loans/api";

type ContactPicker = Navigator & { contacts?: { select: (properties: ("name" | "tel")[], options?: { multiple?: boolean }) => Promise<Array<{ name?: string[]; tel?: string[] }>> } };
function PersonEditor({ personId, initial }: { personId?: string; initial?: { name: string; note: string | null; phone_number: string } }) { const router = useRouter(); const queryClient = useQueryClient(); const [name, setName] = useState(initial?.name ?? ""); const [phone, setPhone] = useState(initial?.phone_number ?? ""); const [note, setNote] = useState(initial?.note ?? ""); const [error, setError] = useState<string | null>(null); const [contactMessage, setContactMessage] = useState<string | null>(null); const save = useMutation({ mutationFn: async () => { if (!name.trim() || !phone.trim()) throw new Error("Enter a contact name and phone number."); const payload = { name: name.trim(), note: note.trim() || null, phone_number: phone.trim() }; return personId ? updateLoanPerson(personId, payload) : createLoanPerson(payload); }, onSuccess: async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ["loan-people"] }), queryClient.invalidateQueries({ queryKey: ["loans"] })]); router.replace("/loan/people" as Route); }, onError: (cause) => setError(cause instanceof Error ? cause.message : "Unable to save this contact.") }); async function pickContact() { setContactMessage(null); const contacts = (navigator as ContactPicker).contacts; if (!contacts?.select) { setContactMessage("Contact picking is not available in this browser."); return; } try { const [contact] = await contacts.select(["name", "tel"], { multiple: false }); if (!contact) { setContactMessage("No contact selected."); return; } const nextName = contact.name?.find(Boolean)?.trim() ?? ""; const nextPhone = contact.tel?.find(Boolean)?.trim() ?? ""; if (nextName) setName(nextName); if (nextPhone) setPhone(nextPhone); setContactMessage(nextName || nextPhone ? "Contact details filled." : "Selected contact has no name or phone number."); } catch { setContactMessage("Contact selection was cancelled or unavailable."); } } function submit(event: FormEvent) { event.preventDefault(); setError(null); save.mutate(); }
  return <form className="loan-form" onSubmit={submit}><section className="loan-form-intro"><p className="eyebrow">LOAN CONTACT</p><h2>{personId ? "Keep their details current." : "Start with the person, not the debt."}</h2></section><button className="contact-picker-button" onClick={() => void pickContact()} type="button">Select from contacts</button>{contactMessage ? <p className="form-notice">{contactMessage}</p> : null}<div className="form-card"><label className="transaction-field"><span>Name</span><input aria-label="Person name" onChange={(event) => setName(event.target.value)} value={name} /></label><label className="transaction-field"><span>Phone number</span><input aria-label="Person phone" onChange={(event) => setPhone(event.target.value)} value={phone} /></label><label className="transaction-field"><span>Note (optional)</span><textarea aria-label="Person note" onChange={(event) => setNote(event.target.value)} rows={3} value={note} /></label></div>{error ? <p className="form-error" role="alert">{error}</p> : null}<button className="save-transaction-button" disabled={save.isPending} type="submit">{save.isPending ? "Saving…" : personId ? "Save contact" : "Add contact"}</button></form>; }
export function PersonForm({ personId }: { personId?: string }) { const person = useQuery({ queryFn: () => getLoanPerson(personId!), enabled: Boolean(personId), queryKey: ["loan-person", personId] }); return <MobileShell><div className="standard-page loan-person-form-page"><PageHeader backHref={"/loan/people" as Route} title={personId ? "Edit contact" : "New contact"} />{personId && person.isPending ? <div aria-busy="true" className="transaction-form-skeleton" /> : null}{person.isError ? <section className="transaction-history-error" role="alert"><strong>Couldn’t load this contact</strong><p>{person.error.message}</p><button onClick={() => void person.refetch()} type="button">Try again</button></section> : null}{(!personId || person.data) ? <PersonEditor initial={person.data} key={person.dataUpdatedAt} personId={personId} /> : null}</div></MobileShell>; }
