"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarClock, Landmark, PauseCircle, Pencil, PlayCircle, Tags, Trash2 } from "lucide-react";
import type { Route } from "next";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

import { MobileShell } from "@/components/layout/mobile-shell";
import { PageHeader } from "@/components/layout/page-header";
import { Drawer, DrawerClose, DrawerContent, DrawerDescription, DrawerFooter, DrawerHeader, DrawerTitle } from "@/components/ui/drawer";
import { changeRecurringState, deleteRecurringRule, getRecurringEditorData } from "@/lib/recurring/api";
import { formatRecurringDate, recurringCadence, recurringTitle } from "@/lib/recurring/utils";
import { formatMoney } from "@/lib/home/view-model";

export function RecurringDetail({ ruleId }: { ruleId: string }) {
  const router = useRouter(); const queryClient = useQueryClient(); const [deleteOpen, setDeleteOpen] = useState(false); const [error, setError] = useState<string | null>(null);
  const detail = useQuery({ queryFn: () => getRecurringEditorData(ruleId), queryKey: ["recurring-detail", ruleId] });
  const state = useMutation({ mutationFn: changeRecurringState, onSuccess: async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ["recurring"] }), queryClient.invalidateQueries({ queryKey: ["recurring-detail", ruleId] })]); } });
  const remove = useMutation({ mutationFn: deleteRecurringRule }); const rule = detail.data?.rule; const account = detail.data?.accounts.find((item) => item.id === rule?.account_id); const category = detail.data?.categories.find((item) => item.id === rule?.category_id);
  async function confirmDelete() { if (!rule) return; setError(null); try { await remove.mutateAsync(rule.id); await queryClient.invalidateQueries({ queryKey: ["recurring"] }); router.replace("/transaction/recurring" as Route); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to delete this schedule."); } }
  return <MobileShell><div className="standard-page recurring-detail-page"><PageHeader backHref={"/transaction/recurring" as Route} title="Recurring details" />{detail.isPending ? <div aria-busy="true" className="transaction-form-skeleton" /> : null}{detail.isError ? <section className="transaction-history-error" role="alert"><strong>Couldn’t load this schedule</strong><p>{detail.error.message}</p><button onClick={() => void detail.refetch()} type="button">Try again</button></section> : null}{rule ? <><section className={`recurring-detail-hero recurring-detail-hero--${rule.transaction_type}`}><span><CalendarClock aria-hidden="true" size={25} /></span><p>{rule.transaction_type} · {rule.status}</p><h2>{recurringTitle(rule)}</h2><strong>{formatMoney(rule.amount, rule.currency)}</strong></section><section className="transaction-detail-facts"><div><CalendarClock aria-hidden="true" size={17} /><span>Schedule</span><strong>{recurringCadence(rule)}</strong></div><div><Landmark aria-hidden="true" size={17} /><span>Account</span><strong>{account?.name ?? "Account"}</strong></div><div><Tags aria-hidden="true" size={17} /><span>Category</span><strong>{category?.name ?? rule.transaction_type}</strong></div><div><CalendarClock aria-hidden="true" size={17} /><span>Next run</span><strong>{formatRecurringDate(rule.next_run_at, rule.timezone)}</strong></div></section><section className="recurring-detail-actions"><Link href={`/transaction/recurring/${rule.id}/edit` as Route}><Pencil aria-hidden="true" size={17} />Edit schedule</Link>{rule.status !== "archived" ? <button disabled={state.isPending} onClick={() => void state.mutateAsync(rule)} type="button">{rule.status === "paused" ? <PlayCircle aria-hidden="true" size={17} /> : <PauseCircle aria-hidden="true" size={17} />}{state.isPending ? "Updating…" : rule.status === "paused" ? "Resume schedule" : "Pause schedule"}</button> : null}<button className="recurring-delete" onClick={() => setDeleteOpen(true)} type="button"><Trash2 aria-hidden="true" size={17} />Delete schedule</button></section></> : null}<Drawer onOpenChange={setDeleteOpen} open={deleteOpen}><DrawerContent><DrawerHeader><DrawerTitle>Delete this recurring item?</DrawerTitle><DrawerDescription>This permanently stops future reminders. It does not create a transaction or change your balance.</DrawerDescription></DrawerHeader>{error ? <p className="drawer-error" role="alert">{error}</p> : null}<DrawerFooter><button className="drawer-danger-button" disabled={remove.isPending} onClick={() => void confirmDelete()} type="button">{remove.isPending ? "Deleting…" : "Delete schedule"}</button><DrawerClose asChild><button className="drawer-close-button" type="button">Keep schedule</button></DrawerClose></DrawerFooter></DrawerContent></Drawer></div></MobileShell>;
}
